# Generated by Django 4.1.3 on 2023-10-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosLimpios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateField()),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('ciiu', models.IntegerField()),
                ('valor_transaccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Datos Limpios',
            },
        ),
    ]
