# Generated by Django 4.2.6 on 2023-11-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateField()),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('ciiu', models.IntegerField()),
                ('valor_transaccion', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('funcionario', models.CharField(max_length=255)),
                ('tipo_de_persona', models.CharField(max_length=10)),
                ('medio_de_pago', models.CharField(max_length=20)),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean.contraparte')),
            ],
            options={
                'verbose_name': 'P_limpio',
                'verbose_name_plural': 'P_Limpios',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateField()),
                ('nit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('ciiu', models.IntegerField()),
                ('valor_transaccion', models.DecimalField(decimal_places=2, max_digits=30)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('funcionario', models.CharField(max_length=255)),
                ('tipo_de_persona', models.CharField(max_length=10)),
                ('medio_de_pago', models.CharField(max_length=20)),
                ('canal_de_distribucion', models.CharField(max_length=255)),
                ('medio_de_venta', models.CharField(max_length=255)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('alarmas', models.CharField(blank=True, max_length=255, null=True)),
                ('contraparte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clean.contraparte')),
            ],
            options={
                'verbose_name': 'Cliente_limpio',
                'verbose_name_plural': 'Cliente_Limpios',
            },
        ),
    ]
