# Generated by Django 4.1.3 on 2023-10-20 20:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoslimpios',
            options={'verbose_name': 'Dato_limpio', 'verbose_name_plural': 'Datos_Limpios'},
        ),
        migrations.AddField(
            model_name='datoslimpios',
            name='fecha_conversion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
