# Generated by Django 4.2.6 on 2023-11-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ciiu', models.CharField(max_length=255)),
                ('seccion', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor_riesgo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('divipola', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('valor_riesgo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Generales',
        ),
    ]
