# Generated by Django 4.2.6 on 2023-11-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_rename_nombre_contraparte_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='contraparte',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='contraparte',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Contraparte',
        ),
    ]
