# Generated by Django 4.2.6 on 2023-10-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0002_alter_datoslimpios_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoslimpios',
            name='fecha_conversion',
        ),
        migrations.AddField(
            model_name='datoslimpios',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datoslimpios',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
