# Generated by Django 4.2.6 on 2023-10-21 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_remove_datoslimpios_fecha_conversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoslimpios',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='datoslimpios',
            name='mes',
        ),
        migrations.AddField(
            model_name='datoslimpios',
            name='fecha_conversion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
