# Generated by Django 4.2.6 on 2023-11-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0003_alter_clientes_contraparte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contraparte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clean.contraparte'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='contraparte',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clean.contraparte'),
        ),
    ]
