# Generated by Django 4.2.6 on 2023-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_remove_datoslimpios_ano_remove_datoslimpios_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslimpios',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datoslimpios',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
