# Generated by Django 4.2.6 on 2023-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0004_contraparte_alter_clientes_contraparte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='contraparte',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], default='Cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='contraparte',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], default='Proveedor', max_length=10),
        ),
    ]
