# Generated by Django 4.1.3 on 2023-11-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0005_alter_clientes_contraparte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='funcionario',
            new_name='detalle',
        ),
    ]
