# Generated by Django 4.2.6 on 2023-10-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0005_datoslimpios_ano_datoslimpios_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoslimpios',
            name='fecha_conversion',
        ),
    ]
