# Generated by Django 4.2.6 on 2023-10-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0006_remove_datoslimpios_fecha_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslimpios',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
