# Generated by Django 4.1.3 on 2023-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0006_rename_funcionario_proveedores_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='alarmas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
