# Generated by Django 4.2.6 on 2023-10-25 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0007_datoslimpios_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoslimpios',
            name='contraparte',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
