# Generated by Django 4.2.6 on 2023-11-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0008_generales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generales',
            options={'verbose_name': 'general', 'verbose_name_plural': 'generales'},
        ),
        migrations.RenameField(
            model_name='generales',
            old_name='categoria',
            new_name='Categoría',
        ),
        migrations.RenameField(
            model_name='generales',
            old_name='divipola',
            new_name='Divipola',
        ),
        migrations.RenameField(
            model_name='generales',
            old_name='valor_riesgo',
            new_name='calor_riesgo',
        ),
    ]
