# Generated by Django 4.2.6 on 2023-10-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0008_datoslimpios_contraparte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoslimpios',
            name='contraparte',
        ),
    ]
