# Generated by Django 4.2.6 on 2023-11-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0009_alter_generales_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generales',
            old_name='calor_riesgo',
            new_name='valor_riesgo',
        ),
    ]
