# Generated by Django 4.2.6 on 2023-11-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0010_rename_calor_riesgo_generales_valor_riesgo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generales',
            old_name='Categoría',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='generales',
            old_name='Divipola',
            new_name='divipola',
        ),
    ]
