# Generated by Django 4.2.6 on 2023-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0011_clientes_proveedores_delete_datoslimpios'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='alarmas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
