# Generated by Django 4.2.6 on 2023-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0011_rename_categoría_generales_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Concatenado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='SinCorr_Ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='SinCorrespondencia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
