# Generated by Django 4.2.6 on 2023-11-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0012_clientes_concatenado_clientes_sincorr_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='Concatenado',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='SinCorr_Ciudad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='SinCorrespondencia',
        ),
    ]
