# Generated by Django 4.2.6 on 2023-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clean', '0013_remove_clientes_concatenado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Concatenado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='SinCorr_Ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='SinCorrespondencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
